### ISSUE TITLE
Link down

### ISSUE THREAD

**Issue by Bimo99B9** [weihui1308/PAA#2]
The link to the code for the Naturalistic Physical Adversarial Patch for Object Detectors is broken. I couldn't find it anywhere else, so it would be great if you have it. Otherwise the link should be removed.

Daniel

**Comment by weihui1308** [comment]
The link is: https://github.com/gordonjun2/Naturalistic-Adversarial-Patch

Thank you for your comments.

**Comment by Bimo99B9** [comment]
Thank you for your help!
